dist: trusty
sudo: required
language: node_js
node_js:
  - "8.12.0"
cache: npm
before_install:
  - sudo apt-get install -y libusb-1.0-0 libusb-1.0-0-dev libudev-dev
  - sudo apt-add-repository ppa:bitcoin/bitcoin -y
  - sudo apt-get update
  - sudo apt-get install bitcoind -y

apt_packages:
  - bitcoind

before_script:
  - yarn global add ganache-cli
  - mkdir -p /home/travis/.bitcoin && cp bitcoin.conf /home/travis/.bitcoin/bitcoin.conf
  - bitcoind -reindex -txindex -regtest -daemon -rpcport=18443 -rpcuser=bitcoin -rpcpassword=local321 -deprecatedrpc=signrawtransaction
  - CI=false ganache-cli -k petersburg > /dev/null &
  - export NODE_OPTIONS="--max-old-space-size=8192"
  - cd node_modules/@atomicloans/eth-contracts && truffle migrate && mv addresses.json ../../../src/config/addresses/test.json && cd -
  - CI=false npm run arbiter:test
  - CI=false npm run lender:test

jobs:
  include:
    - stage: Test
      script:
        - CI=false npm run test:lender:funds
